bootstrap:
  - name: playboy
    box: generic/ubuntu1804
    hostname: playboy
    ip: 192.168.1.200
    memory: 2048
    cpu: 2

nodes:
  - name: node-1
    box: generic/ubuntu1804
    hostname: node-1
    ip: 192.168.1.201
    port: 2201
    memory: 4096
    cpu: 4
  - name: node-2
    box: generic/ubuntu1804
    hostname: node-2
    ip: 192.168.1.202
    port: 2202
    memory: 4096
    cpu: 4
  - name: node-3
    box: generic/ubuntu1804
    hostname: node-3
    ip: 192.168.1.203
    port: 2203
    memory: 4096
    cpu: 4
  - name: node-4
    box: generic/ubuntu1804
    hostname: node-4
    ip: 192.168.1.204
    port: 2204
    memory: 4096
    cpu: 4
  - name: node-5
    box: generic/ubuntu1804
    hostname: node-5
    ip: 192.168.1.205
    port: 2205
    memory: 4096
    cpu: 4
  
